POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "The name or number is missing"
}


###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "number": "400"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
      "name": "Arto Hellas", 
      "number": "name already exists in the phonebook"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Firstname Lastname",
    "number": "05-00-1234567"
}
